#VERSION: 0.0.2

---
- hosts: all
  become: True
  vars:
    url: 'https://github.com/movimento-sem-terra/site-novo'
    app_name: 'site'
    app_dir: '/var/apps/'
  tasks:
  - name: Create the project directory.
    file: state=directory path={{ app_dir }} recurse=yes mode=0644
  - name: checkout git project
    git: repo={{ url }}
       dest='{{ app_dir }}{{ app_name }}'
       force=yes
