---
- hosts: all
  become: yes
  become_user: ratox
  vars_files:
  - ../files/vars.yml
  - ../files/env.yml
  vars:
  - service_dir: /home/ratox/authentication-service
  - log_path: /var/log/forever/authentication.log
  tasks:

  - name: checkout git project
    git: repo='{{ item.git_url }}' dest='{{ service_dir }}' force=yes version=master
    with_items:
      - { git_url: 'https://github.com/marighella/authentication' }

  - name: run npm install to dev
    command: npm install --no-optional
    args:
        chdir: "{{ service_dir }}"
    when: "'dev' in group_names"

  - name: run npm install to production
    npm: path={{ service_dir }}
    when: "'dev' not in group_names"

  - name: Ensure log folder exists
    become: yes
    become_user: root
    file:
      path: /var/log/forever
      state: directory
      owner: www-data
      group: www-data
      mode: u=rwX,g=rwX,o=r

  - name: "Check list of Node.js apps running."
    command: forever list
    register: forever_list
    become: ratox
    changed_when: false
    environment:
      PATH: /home/ratox/.npm-global/bin:{{ ansible_env.PATH }}

  - name: "Start file-service.js app."
    become: ratox
    command: forever start -a -l {{ log_path }} -w --watchDirectory "{{ service_dir }}" "{{ service_dir }}/start.js"
    environment:
      GITHUB_CLIENT_ID: "{{ stage.github_client_id }}"
      GITHUB_SECRET_KEY: "{{ stage.github_client_secret }}"
      SECRET_JWT: "{{ stage.secret_jwt }}"
      API_APP_PORT: "{{ api_app_port }}"
    when: "forever_list.stdout.find('{{ service_dir }}/start.js') == -1"
