# main.yml
---
- hosts: all
  become: yes
  become_user: ratox
  vars:
  - backend_dir: ~/backend
  tasks:

  - name: checkout git project
    git: repo='{{ item.git_url }}' dest='{{ backend_dir }}' force=yes
    with_items:
      - { git_url: 'https://github.com/marighella/backend' }

  - name: run npm install
    npm: path={{ backend_dir }}

- hosts: dev
  become: yes
  become_user: ratox
  vars:
  - backend_dir: ~/backend
  tasks:
  - name: run npm install to dev
    npm: path={{ backend_dir }} production=no

  - name: run the tests
    script: {{ backend_dir }}/node_modules/jasmine/bin/jasmine.js

  - name: run npm install to dev
    npm: path={{ backend_dir }} production=no
