# main.yml
---
- hosts: all
  become: True
  become_user: ratox
  vars:
    app_dir: '~'
  tasks:

  - name: Create the project directory.
    file: state=directory path={{ app_dir }} recurse=yes mode="u=rwx,g=rx,o=rx" owner=ratox group=www-data

  - name: checkout git project
    git: repo='{{ item.git_url }}' dest='{{ app_dir }}/{{ item.name }}' force=yes depth=1
    with_items:
      - { git_url: 'https://github.com/movimento-sem-terra/site-novo', name: 'jekyll-site' }

  - name: Rvm set defaults
    shell: 'bash -lc "rvm use 2.1.5 --default"'

  - name: Run bundle
    bundler: state=present chdir='{{ app_dir }}/jekyll-site' gem_path="~/.gem"

  - name: Setup application
    shell: ./setup
    args:
      chdir: '{{ app_dir }}/jekyll-site/'
