# frontend.yml
---
- hosts: all
  become: yes
  tasks:
  - name: Permission to read
    file:
      path: /etc/ssl/marighella
      mode: u=rwX,g=r
      recurse: yes
  roles:
  - role: jdauphant.ssl-certs
    ssl_certs_generate_dh_param: true
    ssl_certs_common_name: "marighella"
  - role: ansible-role-nginx
    nginx_configs:
       ssl:
         - ssl_certificate_key "/etc/ssl/marighella/marighella.key"
         - ssl_certificate     "/etc/ssl/marighella/marighella.pem"
    nginx_sites:
       default:
         - listen 80 default_server
         - listen [::]:80 default_server
         - return 301 https://$host$request_uri
       cms:
         - listen 443 ssl
         - server_name *.marighella.io
         - root /var/www
