# frontend.yml
---
- hosts: all
  become: yes
  tasks:
  - name: Permission to read
    file:
      path: /etc/ssl/marighella
      mode: u=rwX,g=r
      recurse: yes
  - name: Ensure frontend folder exists
    file:
      path: /home/ratox/frontend
      state: directory
      owner: ratox
      group: www-data
      mode: u=rwX,g=r,o=r
  roles:
  - role: jdauphant.ssl-certs
    ssl_certs_generate_dh_param: true
    ssl_certs_common_name: "marighella"
  - role: ansible-role-nginx
    nginx_configs:
       ssl:
         - ssl_certificate_key "/etc/ssl/marighella/marighella.key"
         - ssl_certificate     "/etc/ssl/marighella/marighella.pem"
         - ssl_dhparam         "/etc/ssl/marighella/dhparam.pem"
    nginx_sites:
       default:
         - listen 80 default_server
         - listen [::]:80 default_server
         - return 301 https://$host$request_uri
       cms:
         - listen 443 ssl
         - server_name *.marighella.io
         - add_header Strict-Transport-Security "max-age=31536000"
         - ssl_protocols TLSv1.2
         - ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
         - ssl_prefer_server_ciphers on
         - root /home/ratox/frontend
