# frontend.yml
---
- hosts: all
  become: yes
  vars_files:
    - files/env.yml
    - files/vars.yml
  tasks:
  - name: Permission to read
    file:
      path: /etc/ssl/marighella
      mode: u=rwX,g=rX
      recurse: yes
  - name: Ensure frontend folder exists
    file:
      path: /var/www
      state: directory
      owner: www-data
      group: www-data
      mode: u=rwX,g=rwX,o=r
  - name: Create index html
    template:
      src: index.j2
      dest: /var/www/index.html
      owner: www-data
      group: www-data

  roles:
  - role: jdauphant.ssl-certs
    ssl_certs_generate_dh_param: true
    ssl_certs_common_name: "marighella"
  - role: ansible-role-nginx
    nginx_configs:
       ssl:
         - ssl_certificate_key "/etc/ssl/marighella/marighella.key"
         - ssl_certificate     "/etc/ssl/marighella/marighella.pem"
         - ssl_dhparam         "/etc/ssl/marighella/dhparam.pem"
    nginx_sites:
       default:
         - listen 80 default_server
         - server_name {{ marighella_server_name }}
         - return 301 https://$server_name$request_uri
       cms:
         - listen 443 ssl http2
         - server_name {{ marighella_server_name }}
         - root /var/www
         - gzip on
         - gzip_vary on
         - gzip_comp_level 2
         - gzip_proxied expired no-cache no-store private auth
         - gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml
         - gzip_disable "MSIE [1-6]\."
         - location /auth {
             proxy_pass http://localhost:{{ authentication_app_port }}/;
           }
         - location /api {
             proxy_pass http://localhost:{{ api_app_port }}/api;
             proxy_pass_request_headers on;
           }
