# site.yml
---
- hosts: all
  vars_files:
    - files/vars.yml
    - files/env.yml
  become: True
  roles:
    - { role: ansible-ssh-hardening, sudo: True }
    - { role: ansible-os-hardening, sudo: True }
