# site.yml
---
- hosts: all
  vars_files:
    - files/vars.yml
    - files/env.yml
  become: True
  tasks:
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ system_packages }}"

  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
    - { role: geerlingguy.nodejs, tags: node }
    - { role: greendayonfire.mongodb }

- include: applications/main.yml
