# site.yml
---
- hosts: all
  vars_files:
    - files/vars.yml
    - files/env.yml
  become: yes
  vars:
  - ansible_ssh_user: ratox
  tasks:
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ system_packages }}"

  roles:
    - { role: geerlingguy.nodejs, tags: node, become: yes }
    - { role: greendayonfire.mongodb, become: yes }

- include: applications/main.yml
