# site.yml
---
- hosts: all
  name: "Update all packages"
  become: yes
  tasks:
  - apt:
      upgrade: safe

- hosts: all
  vars_files:
    - files/vars.yml
    - files/env.yml
  become: yes
  become_user: root
  tasks:
  - name: Install required system packages.
    apt: pkg={{ item }} state=latest
    with_items: "{{ system_packages }}"

  - name: Install  python packages
    pip: name={{ item }}
    with_items: "{{ python_packages }}"

- hosts: all
  become: yes
  tasks:
  - name: Add PPA to nginx
    apt_repository:
      repo: 'ppa:nginx/stable'
  - name: Install nginx stable
    apt: pkg=nginx state=latest


- hosts: all
  become: yes
  vars_files:
    - files/vars.yml
    - files/env.yml
  tasks:
    - name: Configure repository
      shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - name: Install node 7
      apt: pkg=nodejs state=latest
  roles:
    - role: greendayonfire.mongodb

- hosts: all
  become: yes
  tasks:
  - name: Set permissions to node modules to ratox
    file:
      path: /home/ratox/.npm-global
      state: directory
      owner: ratox
      group: www-data
      mode: u=rwX,g=rw,o=r
  - name: Change npm global prefix
    command: npm config set prefix '/home/ratox/.npm-global'
  - name: Ensure the PATH is in profile file
    lineinfile:
      dest: /home/ratox/.profile
      regexp: '^\.npm-global'
      line: "export PATH=/home/ratox/.npm-global/bin:$PATH"

- hosts: all
  become: yes
  tasks:
  - name: Install Bower and Grunt
    npm: name={{ item }} state=present global=yes
    with_items:
    - npm
    - forever
    - bower
    - grunt
    - grunt-cli

- hosts: all
  become: yes
  roles:
    - {
        role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.3'],
        rvm1_user: 'ratox'
      }
