# user.yml
---
- hosts: all
  remote_user: root
  vars_files:
    - files/vars.yml
    - files/env.yml
  become: True
  tasks:
  - name: Create ratox user :P
    user:
      name: ratox
      groups: sudo,www-data,ssh
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/ratox_user
      password: "{{ user_pass }}"
      shell: /bin/bash
      update_password: on_create

  - name: Set up authorized_keys for the ratox user
    authorized_key: user=ratox key="{{ item }}" manage_dir=no
    with_file:
      - files/ratox
